const { value: pais } = Swal.fire({
  title: "Welcome!",
  text: "Test The Incredible Predictorium",
  html: '<b class="red">to The Incredible Predictorium 🔷 </b>',
  icon: "success",
  confirmButtonText: "Select",
  footer: '<span class="red">100 % made with 💗</span>',
  width: "50%",
  padding: "1rem",
  backdrop: true,
  timer: 50000,
  timerProgressBar: true,
  input: "select",
  inputPlaceholder: "Country",
  inputValue: "",
  inputOptions: {
    austria: "Austria",
    azerbajan: "Azerbaijan",
    bahamas: "Bahamas",
    bahrain: "Bahrain",
    bangladesh: "Bangladesh",
    barbados: "Barbados",
    belarus: "Belarus",
    belgium: "Belgium",
    belize: "Belize",
    benin: "Benin",
    bhutan: "Bhutan",
    bolivia: "Bolivia",
    bosniaAndHerzegovina: "Bosnia and Herzegovina",
    botswana: "Botswana",
    brazil: "Brazil",
    brunei: "Brunei",
    bulgaria: "Bulgaria",
    burkinaFaso: "Burkina Faso",
    burundi: "Burundi",
    cambodia: "Cambodia",
    cameroon: "Cameroon",
    canada: "Canada",
    capeVerde: "Cape Verde",
    centralAfricanRepublic: "Central African Republic",
    chad: "Chad",
    chile: "Chile",
    china: "China",
    colombia: "Colombia",
    comoros: "Comoros",
    congo: "Congo, Republic of the",
    congoDemocraticRepublic: "Congo, Democratic Republic of the",
    costaRica: "Costa Rica",
    cote: "Cote dIvoire",
    croatia: "Croatia",
    cuba: "Cuba",
    cyprus: "Cyprus",
    czechRepublic: "Czech Republic",
    denmark: "Denmark",
    djibouti: "Djibouti",
    dominica: "Dominica",
    dominicanRepublic: "Dominican Republic",
    eastTimor: "East Timor Timor-Leste",
    ecuador: "Ecuador",
    egypt: "Egypt",
    elSalvador: "El Salvador",
    equatorialGuinea: "Equatorial Guinea",
    eritrea: "Eritrea",
    estonia: "Estonia",
    ethiopia: "Ethiopia",
    fiji: "Fiji",
    finland: "Finland",
    france: "France",
    gabon: "Gabon",
    theGambia: "The Gambia",
    georgia: "Georgia",
    germany: "Germany",
    ghana: "Ghana",
    greece: "Greece",
    grenada: "Grenada",
    guatemala: "Guatemala",
    guinea: "Guinea",
    guineaBissau: "Guinea-Bissau",
    guyana: "Guyana",
    haiti: "Haiti",
    honduras: "Honduras",
    hungary: "Hungary",
    iceland: "Iceland",
    india: "India",
    indonesia: "Indonesia",
    iran: "Iran",
    iraq: "Iraq",
    ireland: "Ireland",
    israel: "Israel",
    italy: "Italy",
    jamaica: "Jamaica",
    japan: "Japan",
    jordan: "Jordan",
    kazakhstan: "Kazakhstan",
    kenya: "Kenya",
    kiribati: "Kiribati",
    koreaNorth: "Korea, North",
    koreaSouth: "Korea, South",
    kosovo: "Kosovo",
    kuwait: "Kuwait",
    Kyrgyzstan: "Kyrgyzstan",
    laos: "Laos",
    latvia: "Latvia",
    lebanon: "Lebanon",
    lesotho: "Lesotho",
    liberia: "Liberia",
    libya: "Libya",
    leichtenstein: "Liechtenstein",
    lithuania: "Lithuania",
    luxemburgo: "Luxembourg",
    macedonia: "Macedonia",
    madagascar: "Madagascar",
    malawi: "Malawi",
    malasya: "Malaysia",
    maldives: "Maldives",
    mali: "Mali",
    malta: "Malta",
    marshallIslands: "Marshall Islands",
    mauritania: "Mauritania",
    mauritius: "Mauritius",
    mexico: "Mexico",
    micronesia: "Micronesia, Federated States of",
    moldova: "Moldova",
    monaco: "Monaco",
    mongolia: "Mongolia",
    montenegro: "Montenegro",
    moroco: "Morocco",
    mozambique: "Mozambique",
    myanmarBurma: "Myanmar Burma",
    namibia: "Namibia",
    nauru: "Nauru",
    nepal: "Nepal",
    netherlands: "Netherlands",
    newZealand: "New Zealand",
    nicaragua: "Nicaragua",
    niger: "Niger",
    nigeria: "Nigeria",
    norway: "Norway",
    oman: "Oman",
    pakistan: "Pakistan",
    palau: "Palau",
    panama: "Panama",
    papauNewGuinea: "Papua New Guinea",
    paraguay: "Paraguay",
    preu: "Peru",
    philippines: "Philippines",
    poland: "Poland",
    portugal: "Portugal",
    qatar: "Qatar",
    romania: "Romania",
    russia: "Russia",
    rwanda: "Rwanda",
    saintKitts: "Saint Kitts and Nevis",
    saintLucia: "Saint Lucia",
    saintVincent: "Saint Vincent and the Grenadines",
    samoa: "Samoa",
    sanMarino: "San Marino",
    saoTome: "Sao Tome and Principe",
    saudiArabia: "Saudi Arabia",
    senegal: "Senegal",
    serbia: "Serbia",
    seychelles: "Seychelles",
    sierraLeone: "Sierra Leone",
    singapore: "Singapore",
    slovakia: "Slovakia",
    slovenia: "Slovenia",
    solomon: "Solomon Islands",
    somalia: "Somalia",
    southAfrica: "South Africa",
    southSudan: "South Sudan",
    spain: "Spain",
    sriLanka: "Sri Lanka",
    sudan: "Sudan",
    suriname: "Suriname",
    swaziland: "Swaziland",
    sweden: "Sweden",
    switzerland: "Switzerland",
    syria: "Syria",
    taiwan: "Taiwan",
    tajikistan: "Tajikistan",
    tanzania: "Tanzania",
    thailand: "Thailand",
    togo: "Togo",
    tonga: "Tonga",
    trinidadAndTobago: "Trinidad and Tobago",
    tunisia: "Tunisia",
    turkey: "Turkey",
    turmekistan: "Turkmenistan",
    tuvalu: "Tuvalu",
    uganda: "Uganda",
    ukraine: "Ukraine",
    unitedArabEmirates: "United Arab Emirates",
    unitedKingdom: "United Kingdom",
    usa: "United States of America",
    uruguay: "Uruguay",
    uzbekistan: "Uzbekistan",
    vanatu: "Vanuatu",
    vatican: "Vatican City",
    venezuela: "Venezuela",
    vietnam: "Vietnam",
    yemen: "Yemen",
    zambia: "Zambia",
    zimbabwe: "Zimbabwe",
  },
});
